language: python
python:
  - "3.6"
  #- "3.7" commented due to travis distrib install error / permission denied
# command to install dependencies
install:
  - pip install tox codecov
# command to run tests
script:
  - tox -v
after_success:
  - codecov
