language: python

matrix:
  include:
    - python: 3.6
      dist: trusty
      sudo: false
      env: TOXENV=py36
    - python: 3.7
      dist: xenial
      sudo: true
      env: TOXENV=py37
# command to install dependencies
install:
  - pip install tox codecov
# command to run tests
script:
  - tox -v
after_success:
  - codecov
